version: '2'

services:
  tshirtshop:
    build: ./
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/tshirtshop
    ports:
      - '3313:8000'
    environment:
        - DJANGO_SETTINGS_MODULE=tshirtshop.settings
